version: 2
sources:
  - name: common
    database: "{{ env_var('PROJECT_ID') }}"
    loader: airflow
    tables:
      - name: us_holidays
        columns:
          - name: date
            data_type: date
            meta:
              mode: REQUIRED
          - name: name
            data_type: STRING