name: Main
run-name: ${{ github.ref.name }}
on:
  push:
    branches:
      - main

env:
  DBT_DIR: dbt
  PROJECT_ID: mv-stg-etl
jobs:
  check-code:
    name: check-code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ruff check
        run: |
          pip install -q ruff
          ruff check --force-exclude --exclude='${{ env.DBT_DIR }}' --fix --exit-non-zero-on-fix
          ruff format --force-exclude

  check-dbt:
    name: check-dbt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: DBT test
        working-directory: ${{ env.DBT_DIR }}
        run: |
          pip install -q dbt-bigquery
          dbt deps --log-level error --no-send-anonymous-usage-stats
          dbt compile
